steps:
  # Build Docker image from dockerfile
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/video-processing-service", "."]
    dir: "video-processing-service"

  # Push Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/video-processing-service"]

  # 3️Deploy Docker image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy video-processing-service \
          --image gcr.io/$PROJECT_ID/video-processing-service \
          --min-instances=0 \
          --max-instances=1 \
          --cpu=1 \
          --region us-west1 \
          --platform managed \
          --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
